CREATE TABLE IF NOT EXISTS habilidades (
    ID_HABILIDADE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NM_HABILIDADE VARCHAR(50) NOT NULL,
    ID_TIPO_HABILIDADE INT NOT NULL,
    CONSTRAINT fk_habilidades_tipos FOREIGN KEY (ID_TIPO_HABILIDADE) REFERENCES tipo_habilidades (ID_TIPO_HABILIDADE)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
);