CREATE TABLE IF NOT EXISTS candidato_habilidade (
    ID_CANDIDATO_HABILIDADE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_HABILIDADE INT NOT NULL,
    ID_CANDIDATO INT NOT NULL,
    CONSTRAINT fk_candidato_habilidade_habilidades_1 FOREIGN KEY (ID_HABILIDADE) REFERENCES habilidades (ID_HABILIDADE)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
    CONSTRAINT fk_candidato_habilidade_candidatos_1 FOREIGN KEY (ID_CANDIDATO) REFERENCES candidatos (ID_CANDIDATO)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
);