CREATE TABLE IF NOT EXISTS candidato_certificacao (
    ID_CANDIDATO_CERTIFICACAO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_CANDIDATO INT NOT NULL,
    ID_CERTIFICACAO INT NOT NULL,
    CONSTRAINT fk_candidato_certificacao_candidatos_2 FOREIGN KEY (ID_CANDIDATO) REFERENCES candidatos (ID_CANDIDATO)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
    CONSTRAINT fk_candidato_certificacao_certificacoes_1 FOREIGN KEY (ID_CERTIFICACAO) REFERENCES certificacoes (ID_CERTIFICACAO)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
);